### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by Nob0dyImportant** [ZacNVR/server-utils#28]
Is there such a thing where a player who joins a server is immediately teleported to a given location??

**Comment by ZacNVR** [comment]
Server Utilities does not provide such a feature by default, but it does provide the means to implement such a function. You would need to:
1. Put Server Utilities on the server
2. Create another data pack with a function that teleports `@s` to the desired location
3. Put the above function in the tag `#server_utils:player_joined`

All functions in `#server_utils:player_joined` run every time a player joins the server. It also runs as the player who joined.

Hope that helps!
